### ISSUE TITLE
Typo in "Left Point" shape

### ISSUE THREAD

**Issue by turuslan** [bennettfeely/Clippy#15]
In https://github.com/bennettfeely/Clippy/blob/master/dev/clip.js#L61

It is `[[25,0],[100,`**`1`**`],[100,100],[25,100],[0,50]]`
Should be `[[25,0],[100,`**`0`**`],[100,100],[25,100],[0,50]]`

**Comment by bennettfeely** [comment]
Well it's been a year and a half but I just fixed this. Thanks for the heads up!
