### ISSUE TITLE
Does not appear to work in Safari

### ISSUE THREAD

**Issue by eat-sleep-code** [bennettfeely/clippy#16]
https://bennettfeely.com/clippy/ does not appear to work correctly in Safari.   The shapes are all rendered as squares and do not mask the image.

![Screen Shot 2020-01-17 at 9 51 19 AM](https://user-images.githubusercontent.com/3846471/72630135-eefb6680-390e-11ea-8ba2-0d46c30ea94a.png)

This is occurring on Safari on a fully-patched version of Catalina:

![Screen Shot 2020-01-17 at 9 52 51 AM](https://user-images.githubusercontent.com/3846471/72630272-3e419700-390f-11ea-8a73-6b8ee67521eb.png)

**Comment by vikramsoni2** [comment]
Its not adding -webkit-clip-path: property to the element. Thats why its not working for Safari.
