### ISSUE TITLE
Request - Smooth edges

### ISSUE THREAD

**Issue by rknell** [bennettfeely/Clippy#6]
Hi,

Once I work out how to do it i might make a pull request, but if there is a way to smooth edges that would be great. My use case is a hexagon from a client ie:

<img width="247" alt="screen shot 2015-07-24 at 4 44 27 pm" src="https://cloud.githubusercontent.com/assets/5875053/8869248/dcc0c7bc-3224-11e5-8094-a36b314e6045.png">

For the moment I used the site and will hand code the edges, but need to research the math to do it the right way

**Comment by thebabydino** [comment]
@rknell Quick and dirty Sass demo of how this would work http://codepen.io/thebabydino/pen/XbxKbL?editors=010

**Comment by rknell** [comment]
Wow did you just whip that up for this? I need to sharpen my Sass skills! Thanks
