### ISSUE TITLE
Support enabled in Firefox 53

### ISSUE THREAD

**Issue by simevidas** [bennettfeely/Clippy#8]
I just visited Clippy in Firefox Nightly, and all the shapes render correctly. I checked the relevant flag in about:config, and it has indeed been enabled. The “No support” message should therefore no longer be displayed in Firefox 53+. I can make a PR.

**Comment by adamopenweb** [comment]
Oh cool, just stumbled on this today. I don't mind making a PR for this either. @simevidas do you still want to do it?

**Comment by simevidas** [comment]
Go ahead :)

**Comment by adamopenweb** [comment]
@bennettfeely I was going to create a PR for this issue but noticed that master is out of date with what's on the website.

We have:
```js
  if(browser == "mozilla") {
    var browser = "Firefox";
    $html.addClass("no-support");
}
```
here: https://github.com/bennettfeely/Clippy/blob/master/dev/clip.js#L280

Then on the website it's been updated to:

```js
 if(browser == "mozilla") {
    if(version > 53) {
      var browser = "Firefox";
      $html.addClass("no-support");
    }
  }
```
in: http://bennettfeely.com/clippy/dev/clip.js

If we can just change this to:

```js
 if(browser == "mozilla") {
    if(version < 54,) {
      var browser = "Firefox";
      $html.addClass("no-support");
    }
  }
```

Then I think we're good. As Firefox has clip path support from 54 onward.

Any chance we can get this updated? 😄

**Comment by tomByrer** [comment]
Fx54 should be due soon....
